const a = {
  "object": "list",
  "data": [
     {
        "id": "cus_Et1pXD32D7xrRk",
        "object": "customer",
        "account_balance": 0,
        "created": 1555276924,
        "currency": "usd",
        "default_source": "card_1EPFlzBLD9LzuEKHeglVBr1O",
        "delinquent": false,
        "description": null,
        "discount": null,
        "email": "devskill2015@yandex.com",
        "invoice_prefix": "511E9C28",
        "invoice_settings": {
           "custom_fields": null,
           "footer": null
        },
        "livemode": false,
        "metadata": {},
        "shipping": null,
        "sources": {
           "object": "list",
           "data": [
              {
                 "id": "card_1EPFlzBLD9LzuEKHeglVBr1O",
                 "object": "card",
                 "address_city": null,
                 "address_country": null,
                 "address_line1": null,
                 "address_line1_check": null,
                 "address_line2": null,
                 "address_state": null,
                 "address_zip": "11601",
                 "address_zip_check": "pass",
                 "brand": "Visa",
                 "country": "US",
                 "customer": "cus_Et1pXD32D7xrRk",
                 "cvc_check": "pass",
                 "dynamic_last4": null,
                 "exp_month": 12,
                 "exp_year": 2023,
                 "fingerprint": "teibVDDc45P880Mx",
                 "funding": "credit",
                 "last4": "4242",
                 "metadata": {},
                 "name": null,
                 "tokenization_method": null
              }
           ],
           "has_more": false,
           "total_count": 1,
           "url": "/v1/customers/cus_Et1pXD32D7xrRk/sources"
        },
        "subscriptions": {
           "object": "list",
           "data": [
              {
                 "id": "sub_Et1s8hHxgYJ4Qo",
                 "object": "subscription",
                 "application_fee_percent": null,
                 "billing": "charge_automatically",
                 "billing_cycle_anchor": 1555277065,
                 "billing_thresholds": null,
                 "cancel_at": null,
                 "cancel_at_period_end": false,
                 "canceled_at": null,
                 "created": 1555277065,
                 "current_period_end": 1555881865,
                 "current_period_start": 1555277065,
                 "customer": "cus_Et1pXD32D7xrRk",
                 "days_until_due": null,
                 "default_source": null,
                 "discount": null,
                 "ended_at": null,
                 "items": {
                    "object": "list",
                    "data": [
                       {
                          "id": "si_Et1sEi6s4DAoRx",
                          "object": "subscription_item",
                          "billing_thresholds": null,
                          "created": 1555277066,
                          "metadata": {},
                          "plan": {
                             "id": "plan_EhNgwjU9ziZFzJ",
                             "object": "plan",
                             "active": true,
                             "aggregate_usage": null,
                             "amount": 1000,
                             "billing_scheme": "per_unit",
                             "created": 1552590548,
                             "currency": "usd",
                             "interval": "week",
                             "interval_count": 1,
                             "livemode": false,
                             "metadata": {},
                             "nickname": null,
                             "product": "prod_EVcMWMKUVclNFj",
                             "tiers": null,
                             "tiers_mode": null,
                             "transform_usage": null,
                             "trial_period_days": null,
                             "usage_type": "licensed"
                          },
                          "quantity": 1,
                          "subscription": "sub_Et1s8hHxgYJ4Qo"
                       }
                    ],
                    "has_more": false,
                    "total_count": 1,
                    "url": "/v1/subscription_items?subscription=sub_Et1s8hHxgYJ4Qo"
                 },
                 "latest_invoice": "in_1EPFoLBLD9LzuEKHQePcx4g3",
                 "livemode": false,
                 "metadata": {},
                 "plan": {
                    "id": "plan_EhNgwjU9ziZFzJ",
                    "object": "plan",
                    "active": true,
                    "aggregate_usage": null,
                    "amount": 1000,
                    "billing_scheme": "per_unit",
                    "created": 1552590548,
                    "currency": "usd",
                    "interval": "week",
                    "interval_count": 1,
                    "livemode": false,
                    "metadata": {},
                    "nickname": null,
                    "product": "prod_EVcMWMKUVclNFj",
                    "tiers": null,
                    "tiers_mode": null,
                    "transform_usage": null,
                    "trial_period_days": null,
                    "usage_type": "licensed"
                 },
                 "quantity": 1,
                 "schedule": null,
                 "start": 1555277065,
                 "status": "active",
                 "tax_percent": null,
                 "trial_end": null,
                 "trial_start": null
              },
              {
                 "id": "sub_Et1rrlFEqfrFhJ",
                 "object": "subscription",
                 "application_fee_percent": null,
                 "billing": "charge_automatically",
                 "billing_cycle_anchor": 1555277007,
                 "billing_thresholds": null,
                 "cancel_at": null,
                 "cancel_at_period_end": false,
                 "canceled_at": null,
                 "created": 1555277007,
                 "current_period_end": 1555881807,
                 "current_period_start": 1555277007,
                 "customer": "cus_Et1pXD32D7xrRk",
                 "days_until_due": null,
                 "default_source": null,
                 "discount": null,
                 "ended_at": null,
                 "items": {
                    "object": "list",
                    "data": [
                       {
                          "id": "si_Et1rNkW8NXloDW",
                          "object": "subscription_item",
                          "billing_thresholds": null,
                          "created": 1555277008,
                          "metadata": {},
                          "plan": {
                             "id": "plan_EWrrihlovtgPdR",
                             "object": "plan",
                             "active": true,
                             "aggregate_usage": null,
                             "amount": 1000,
                             "billing_scheme": "per_unit",
                             "created": 1550165739,
                             "currency": "usd",
                             "interval": "week",
                             "interval_count": 1,
                             "livemode": false,
                             "metadata": {},
                             "nickname": null,
                             "product": "prod_EWrrGx0TsBAzJz",
                             "tiers": null,
                             "tiers_mode": null,
                             "transform_usage": null,
                             "trial_period_days": null,
                             "usage_type": "licensed"
                          },
                          "quantity": 1,
                          "subscription": "sub_Et1rrlFEqfrFhJ"
                       }
                    ],
                    "has_more": false,
                    "total_count": 1,
                    "url": "/v1/subscription_items?subscription=sub_Et1rrlFEqfrFhJ"
                 },
                 "latest_invoice": "in_1EPFnPBLD9LzuEKHG9kLeHfT",
                 "livemode": false,
                 "metadata": {},
                 "plan": {
                    "id": "plan_EWrrihlovtgPdR",
                    "object": "plan",
                    "active": true,
                    "aggregate_usage": null,
                    "amount": 1000,
                    "billing_scheme": "per_unit",
                    "created": 1550165739,
                    "currency": "usd",
                    "interval": "week",
                    "interval_count": 1,
                    "livemode": false,
                    "metadata": {},
                    "nickname": null,
                    "product": "prod_EWrrGx0TsBAzJz",
                    "tiers": null,
                    "tiers_mode": null,
                    "transform_usage": null,
                    "trial_period_days": null,
                    "usage_type": "licensed"
                 },
                 "quantity": 1,
                 "schedule": null,
                 "start": 1555277007,
                 "status": "active",
                 "tax_percent": null,
                 "trial_end": null,
                 "trial_start": null
              },
              {
                 "id": "sub_Et1psYzgB0R6QQ",
                 "object": "subscription",
                 "application_fee_percent": null,
                 "billing": "charge_automatically",
                 "billing_cycle_anchor": 1555276927,
                 "billing_thresholds": null,
                 "cancel_at": null,
                 "cancel_at_period_end": false,
                 "canceled_at": null,
                 "created": 1555276927,
                 "current_period_end": 1555881727,
                 "current_period_start": 1555276927,
                 "customer": "cus_Et1pXD32D7xrRk",
                 "days_until_due": null,
                 "default_source": null,
                 "discount": null,
                 "ended_at": null,
                 "items": {
                    "object": "list",
                    "data": [
                       {
                          "id": "si_Et1pzA6Pl8EO8D",
                          "object": "subscription_item",
                          "billing_thresholds": null,
                          "created": 1555276927,
                          "metadata": {},
                          "plan": {
                             "id": "plan_ErVxsCgl0YE2JY",
                             "object": "plan",
                             "active": true,
                             "aggregate_usage": null,
                             "amount": 10100,
                             "billing_scheme": "per_unit",
                             "created": 1554927732,
                             "currency": "usd",
                             "interval": "week",
                             "interval_count": 1,
                             "livemode": false,
                             "metadata": {},
                             "nickname": null,
                             "product": "prod_Ebjk2V19uo5yKL",
                             "tiers": null,
                             "tiers_mode": null,
                             "transform_usage": null,
                             "trial_period_days": null,
                             "usage_type": "licensed"
                          },
                          "quantity": 1,
                          "subscription": "sub_Et1psYzgB0R6QQ"
                       }
                    ],
                    "has_more": false,
                    "total_count": 1,
                    "url": "/v1/subscription_items?subscription=sub_Et1psYzgB0R6QQ"
                 },
                 "latest_invoice": "in_1EPFm7BLD9LzuEKHRiYTfxwo",
                 "livemode": false,
                 "metadata": {},
                 "plan": {
                    "id": "plan_ErVxsCgl0YE2JY",
                    "object": "plan",
                    "active": true,
                    "aggregate_usage": null,
                    "amount": 10100,
                    "billing_scheme": "per_unit",
                    "created": 1554927732,
                    "currency": "usd",
                    "interval": "week",
                    "interval_count": 1,
                    "livemode": false,
                    "metadata": {},
                    "nickname": null,
                    "product": "prod_Ebjk2V19uo5yKL",
                    "tiers": null,
                    "tiers_mode": null,
                    "transform_usage": null,
                    "trial_period_days": null,
                    "usage_type": "licensed"
                 },
                 "quantity": 1,
                 "schedule": null,
                 "start": 1555276927,
                 "status": "active",
                 "tax_percent": null,
                 "trial_end": null,
                 "trial_start": null
              }
           ],
           "has_more": false,
           "total_count": 3,
           "url": "/v1/customers/cus_Et1pXD32D7xrRk/subscriptions"
        },
        "tax_info": null,
        "tax_info_verification": null
     }
  ],
  "has_more": false,
  "url": "/v1/customers"
}